language: python

sudo: false

install:
    pip install tox

script: tox

notifications:
  on_success: change
  on_failure: always

env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
  - TOXENV=docstrings

matrix:
  allow_failures:
  - env: TOXENV=docstrings
